### ISSUE TITLE
gl prototypes aren't surrounded by extern "C" and so fail to link to c++ code

### ISSUE THREAD

**Issue by ferry-** [anholt/libepoxy#106]
Since commit 0625a74d69f762df8d411bc0451927424aee1f2c where the EPOXY_BEGIN/END_DECLS were introduced, include/gl.h contains the lines

```
#include "epoxy/gl_generated.h"

EPOXY_BEGIN_DECLS

EPOXY_PUBLIC bool epoxy_has_gl_extension(const char *extension);
EPOXY_PUBLIC bool epoxy_is_desktop_gl(void);
EPOXY_PUBLIC int epoxy_gl_version(void);

EPOXY_END_DECLS
```

This causes the epoxy specific prototypes to be surrounded by extern "C",  but not the OpenGL prototypes from include/gl_generated.h. Is this by design? It causes my C++ code to fail to link (windows, msvc 2015).

My fix was to swap the first two lines quoted above.

**Comment by ebassi** [comment]
Mmh, it was definitely not intended, but I'm also not entirely sure the original behaviour was intended either.  :-)

**Comment by ebassi** [comment]
A workaround would be to add the C++ guards around `#include <epoxy/gl.h>` and friends.
