### ISSUE TITLE
Meson build failure

### ISSUE THREAD

**Issue by cromerc** [anholt/libepoxy#120]
Since 1.4.2 building with meson fails. I run this command:
`meson --prefix=/usr --buildtype=release "../libepoxy" -Denable-docs=true`
The error I get is:
Meson encountered an error in file include/epoxy/meson.build, line 24, column 2:
Array as argument 1 contains a non-string.

1.4.1 builds just fine with meson. I can also build 1.4.2 just fine using standard make. But 1.4.2 fails to build with meson.

**Comment by ebassi** [comment]
Which version of Meson is this?

There have been no changes between 1.4.1 and 1.4.2 on that line, and I cannot reproduce the error with Meson 0.39.* and 0.40.*.

**Comment by cromerc** [comment]
I am using 0.38.1 which is the same version listed on the release page for 1.4.2: https://github.com/anholt/libepoxy/releases/tag/1.4.2

I will try with a newer version of meson and see if that helps.

**Comment by cromerc** [comment]
Yep, using meson 0.40 fixes the build. The problem is when using meson 0.38.1.

**Comment by ebassi** [comment]
Thanks for testing; I'll make sure to updated the required version of Meson.
