### ISSUE TITLE
 64bit-portability-issue src/egl_generated_dispatch.c

### ISSUE THREAD

**Issue by zaitor** [anholt/libepoxy#125]
While building libexpoxy-1.4.2 for the yet unreleased openSUSE Leap 42.3, I hit the following 
64bit-portability issue (same for autotools as meson build) in our post build checks.
The issue does not show up on Tubleweed, where we among other things have gcc7 as default compiler. gcc-6 is available for Leap, but same issue shows up if using that instead of gcc-4 (default in Leap).

[   72s] + cd libepoxy-1.4.2
[   72s] + /usr/bin/rm -rf /home/abuild/rpmbuild/BUILDROOT/libepoxy-1.4.2-6.1.x86_64
[   72s] + exit 0
[   72s] ... checking for files with abuild user/group
[   72s] ... running 00-check-install-rpms
[   72s] ... installing all built rpms
[   72s] Preparing packages...
[   72s] libepoxy0-1.4.2-6.1.x86_64
[   72s] libepoxy-devel-1.4.2-6.1.x86_64
[   72s] ... running 01-check-debuginfo
[   72s] ... testing for empty debuginfo packages
[   72s] ... running 02-check-gcc-output
[   72s] ... testing for serious compiler warnings
[   72s]     (using /usr/lib/build/checks-data/check_gcc_output)
[   72s]     (using //.build.log)
[   72s] E: libepoxy 64bit-portability-issue src/egl_generated_dispatch.c:4343, 4344, 4373
[   72s] 
[   72s] cloud104 failed "build libepoxy.spec" at Mon Jun  5 00:28:35 UTC 2017.
[   72s] 
[   72s] ### VM INTERACTION START ###
[   76s] [   57.545878] reboot: Power down
[   83s] ### VM INTERACTION END ###

**Comment by zaitor** [comment]
https://build.opensuse.org/build/home:Zaitor:branches:X11:XOrg/openSUSE_Leap_42.3/x86_64/libepoxy/_log complete buildlog if of intrest.

**Comment by ebassi** [comment]
@zaitor I don't have access to that build log, and it would be helpful if you actually reported what the "64bit portability issues" are on this issue.

**Comment by zaitor** [comment]
@ebassi Sorry! - I was sure the buildlogs were available for people not logged in, will attach it.

as to what the portability issues are, I assume it's this the checker is complaining about:

../test/headerguards.c
[   52s] src/egl_generated_dispatch.c: In function â€˜epoxy_eglQueryDmaBufFormatsEXT_global_rewrite_ptrâ€™:
[   52s] src/egl_generated_dispatch.c:4343:1: warning: passing argument 3 of â€˜epoxy_eglQueryDmaBufFormatsEXTâ€™ makes pointer from integer without a cast [enabled by default]
[   52s]  GEN_THUNKS_RET(EGLBoolean, eglQueryDmaBufFormatsEXT, (EGLDisplay dpy, EGLint max_formats, EGLint *formats, EGLint *num_formats), (dpy, max_formats, *formats, *num_formats))
[   52s]  ^
[   52s] src/egl_generated_dispatch.c:4343:1: note: expected â€˜EGLint *â€™ but argument is of type â€˜EGLintâ€™
[   52s] src/egl_generated_dispatch.c:4343:1: warning: passing argument 4 of â€˜epoxy_eglQueryDmaBufFormatsEXTâ€™ makes pointer from integer without a cast [enabled by default]
[   52s] src/egl_generated_dispatch.c:4343:1: note: expected â€˜EGLint *â€™ but argument is of type â€˜EGLintâ€™
[   52s] src/egl_generated_dispatch.c: In function â€˜epoxy_eglQueryDmaBufModifiersEXT_global_rewrite_ptrâ€™:
[   52s] src/egl_generated_dispatch.c:4344:1: warning: passing argument 4 of â€˜epoxy_eglQueryDmaBufModifiersEXTâ€™ makes pointer from integer without a cast [enabled by default]
[   52s]  GEN_THUNKS_RET(EGLBoolean, eglQueryDmaBufModifiersEXT, (EGLDisplay dpy, EGLint format, EGLint max_modifiers, EGLuint64KHR *modifiers, EGLBoolean *external_only, EGLint *num_modifiers), (dpy, format, max_modifiers, *modifiers, *external_only, *num_modifiers))
[   52s]  ^
[   52s] src/egl_generated_dispatch.c:4344:1: note: expected â€˜EGLuint64KHR *â€™ but argument is of type â€˜EGLuint64KHRâ€™
[   52s] src/egl_generated_dispatch.c:4344:1: warning: passing argument 5 of â€˜epoxy_eglQueryDmaBufModifiersEXTâ€™ makes pointer from integer without a cast [enabled by default]
[   52s] src/egl_generated_dispatch.c:4344:1: note: expected â€˜EGLBoolean *â€™ but argument is of type â€˜EGLBooleanâ€™
[   52s] src/egl_generated_dispatch.c:4344:1: warning: passing argument 6 of â€˜epoxy_eglQueryDmaBufModifiersEXTâ€™ makes pointer from integer without a cast [enabled by default]
[   52s] src/egl_generated_dispatch.c:4344:1: note: expected â€˜EGLint *â€™ but argument is of type â€˜EGLintâ€™
[   52s] src/egl_generated_dispatch.c: In function â€˜epoxy_eglStreamConsumerGLTextureExternalAttribsNV_global_rewrite_ptrâ€™:
[   52s] src/egl_generated_dispatch.c:4373:1: warning: passing argument 3 of â€˜epoxy_eglStreamConsumerGLTextureExternalAttribsNVâ€™ makes pointer from integer without a cast [enabled by default]
[   52s]  GEN_THUNKS_RET(EGLBoolean, eglStreamConsumerGLTextureExternalAttribsNV, (EGLDisplay dpy, EGLStreamKHR stream, EGLAttrib *attrib_list), (dpy, stream, *attrib_list))
[   52s]  ^
[   52s] src/egl_generated_dispatch.c:4373:1: note: expected â€˜EGLAttrib *â€™ but argument is of type â€˜EGLAttribâ€™
[   52s] src/egl_generated_dispatch.c: At top level:
[   52s] cc1: warning: unrecognized command line option "-Wno-int-conversion" [enabled by default]



Please see below file for full log if wanted/needed.
[build-log-noglesv2.txt](https://github.com/anholt/libepoxy/files/1051957/build-log-noglesv2.txt)


Note that this is not a important issue, please handle with that in mind.

**Comment by zaitor** [comment]
1.4.3 release just fixed my issue. Thanks!

**Comment by ebassi** [comment]
Good to know!
