### ISSUE TITLE
`GLVND_GLX_LIB` not defined on OS X

### ISSUE THREAD

**Issue by mwhipple** [anholt/libepoxy#132]
Trying to build the latest on OS X breaks with:
```
error: use of undeclared identifier 'GLVND_GLX_LIB'
        get_dlopen_handle(&api.glx_handle, GLVND_GLX_LIB, false);
```

It looks like the last relevant commit conditionally defines the constant but unconditionally references it:
https://github.com/anholt/libepoxy/commit/759de647298aca23b5d77f7f11e530dc99c08ca9#diff-64008a631b29dfa2d255bc24379b2b52

**Comment by nwnk** [comment]
Fixed in #133 I think
