### ISSUE TITLE
Building error of GTK+ (using jhbuild) : expected expression before « EGLContext » : EGL_NO_CONTEXT

### ISSUE THREAD

**Issue by freeroot** [anholt/libepoxy#135]
From https://bugzilla.gnome.org/show_bug.cgi?id=785893 , issue is due of libepoxy ?

Building error (jhbuild) : expected expression before « EGLContext » : EGL_NO_CONTEXT

In file included from /usr/include/epoxy/egl.h:46:0,
                 from /home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.h:32,
                 from /home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:24:
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c: Dans la fonction « gdk_wayland_gl_context_realize »:
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:179:43: erreur : expected expression before « EGLContext »
                                         : EGL_NO_CONTEXT,
                                           ^
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:200:47: erreur : expected expression before « EGLContext »
                                             : EGL_NO_CONTEXT,
                                               ^
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c: Dans la fonction « gdk_x11_gl_context_dispose »:
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:510:54: erreur : expected expression before « EGLSurface »
         eglMakeCurrent(display_wayland->egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE,
                                                      ^
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:510:70: erreur : expected expression before « EGLSurface »
         eglMakeCurrent(display_wayland->egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE,
                                                                      ^
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:511:24: erreur : expected expression before « EGLContext »
                        EGL_NO_CONTEXT);
                        ^
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c: Dans la fonction « gdk_wayland_display_make_gl_context_current »:
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:534:52: erreur : expected expression before « EGLSurface »
       eglMakeCurrent(display_wayland->egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE,
                                                    ^
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:534:68: erreur : expected expression before « EGLSurface »
       eglMakeCurrent(display_wayland->egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE,
                                                                    ^
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:535:22: erreur : expected expression before « EGLContext »
                      EGL_NO_CONTEXT);
                      ^
/home/***/jhbuild/checkout/gtk+-3/gdk/wayland/gdkglcontext-wayland.c:547:16: erreur : expected expression before « EGLSurface »
  egl_surface = EGL_NO_SURFACE;
                ^
Makefile:702 : la recette pour la cible « gdkglcontext-wayland.lo » a échouée
make[5]: *** [gdkglcontext-wayland.lo] Erreur 1
make[5]: *** Attente des tâches non terminées....
make[5] : on quitte le répertoire « /home/***/.cache/jhbuild/build/gtk+-3/gdk/wayland »
Makefile:609 : la recette pour la cible « all » a échouée
make[4]: *** [all] Erreur 2
make[4] : on quitte le répertoire « /home/***/.cache/jhbuild/build/gtk+-3/gdk/wayland »
Makefile:1652 : la recette pour la cible « all-recursive » a échouée
make[3]: *** [all-recursive] Erreur 1
make[3] : on quitte le répertoire « /home/***/.cache/jhbuild/build/gtk+-3/gdk »
Makefile:1089 : la recette pour la cible « all » a échouée
make[2]: *** [all] Erreur 2
make[2] : on quitte le répertoire « /home/***/.cache/jhbuild/build/gtk+-3/gdk »
Makefile:722 : la recette pour la cible « all-recursive » a échouée
make[1]: *** [all-recursive] Erreur 1
make[1] : on quitte le répertoire « /home/***/.cache/jhbuild/build/gtk+-3 »
Makefile:616 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
*** Error during phase build of gtk+-3: ########## Error running make -j 3  *** [18/21]

**Comment by tomsunchen** [comment]
now i also come across this problem when compiling gtk3. if remove  all  EGL_CAST in registry/egl.xml, for example  change EGL_CAST(EGLint, -1) to ((EGLint)-1), the problem is disappeared.

**Comment by chuchingkai** [comment]
I met this issue too.

**Comment by ebassi** [comment]
Is this still an issue when building with libepoxy from Git? I think this was caused by building libepoxy against an older version of Mesa, and was fixed by commit ebe3a53db1c0bb34e1ca963b95d1f222115f93f8

**Comment by freeroot** [comment]
It works, thanks !
