### ISSUE TITLE
The pkg-config file should declare a Requires.private setting on the GL related libraries it depends.

### ISSUE THREAD

**Issue by clopez** [anholt/libepoxy#139]
On some platforms the GL libraries define some `CFLAGS` on their `pkg-config` file that the build system need to pass when building them, or the build will fail (or will compile an incorrect ifdef).

I have seen this on the following two cases:
 1) The headers of the non-free Vivante driver for Freescale platforms. In this case the EGL `pc` file defines this cflags ```-DLINUX -DEGL_API_FB -DWL_EGL_PLATFORM ```. And if this is not set by the compiler when including `EGL/eglplatform.h` it will generate a fatal build-time error:
```
$ cat testegl.c
#include <epoxy/gl.h>
#include <epoxy/egl.h>

int main(int argc, char **argv)
{
	return 0;
}

$ pkg-config --cflags epoxy
# nothing

$ pkg-config --cflags glesv2 
# nothing

$ pkg-config --cflags egl
-DLINUX -DEGL_API_FB -DWL_EGL_PLATFORM

$ arm-linux-gnueabihf-gcc -I/tmp/sysroots/imx6/usr/include -mfloat-abi=hard --sysroot /tmp/sysroots/imx6/ $(pkg-config --cflags epoxy) testegl.c -c
In file included from /tmp/sysroots/imx6/usr/include/EGL/eglplatform.h:38:0,
                 from /tmp/sysroots/imx6/usr/include/epoxy/egl_generated.h:11,
                 from /tmp/sysroots/imx6/usr/include/epoxy/egl.h:46,
                 from /home/clopez/testegl.c:2:
/tmp/sysroots/imx6/usr/include/EGL/eglvivante.h:266:2: error: #error "Platform not recognized"
 #error "Platform not recognized"
  ^

$ arm-linux-gnueabihf-gcc -I/tmp/sysroots/imx6/usr/include -mfloat-abi=hard --sysroot /tmp/sysroots/imx6/ $(pkg-config --cflags epoxy glesv2 egl) testegl.c -c
# OK

```
 2) Mesa when built with non-x11 support. This is how the `.pc` files that Mesa generates when it is build without X11 support look:
```
$ wget https://mesa.freedesktop.org/archive/17.0.0/mesa-17.0.0.tar.xz
$ tar xfa mesa-17.0.0.tar.xz
$ cd mesa-17.0.0
$ mkdir opt_inst_dir
$ ./configure --prefix=$(pwd)/opt_inst_dir --with-egl-platforms=drm
$ make -j $(nproc) && make install
$ grep -r Cflags opt_inst_dir/lib/pkgconfig
opt_inst_dir/lib/pkgconfig/glesv1_cm.pc:Cflags: -I${includedir}
opt_inst_dir/lib/pkgconfig/egl.pc:Cflags: -I${includedir}  -DMESA_EGL_NO_X11_HEADERS
opt_inst_dir/lib/pkgconfig/gbm.pc:Cflags: -I${includedir}
opt_inst_dir/lib/pkgconfig/glesv2.pc:Cflags: -I${includedir}
opt_inst_dir/lib/pkgconfig/dri.pc:Cflags: -I${includedir}
opt_inst_dir/lib/pkgconfig/gl.pc:Cflags: -I${includedir}  -DMESA_EGL_NO_X11_HEADERS
```

So, the issue is that any program using libepoxy on this systems will fail to build or will build incorrectly because the `CFLAGS` expected defined by the ```.pc``` files of the platform GL headers are not being passed when using epoxy.

This can be done by declaring a `Requires.private` dependency on the `pkg-config` file.

This is the output after applying the following patch to ```epoxy.pc```

```
--- b/tmp/sysroots/imx6/usr/lib/pkgconfig/epoxy.pc	2017-09-19 18:58:44.987929794 +0200
+++ b/tmp/sysroots/imx6/usr/lib/pkgconfig/epoxy.pc	2017-09-19 19:01:17.352519600 +0200
@@ -10,6 +10,7 @@
 Name: epoxy
 Description: epoxy GL dispatch Library
 Version: 1.4.3
+Requires.private: glesv2 egl
 Cflags: -I${includedir}
 Libs: -L${libdir} -lepoxy
 Libs.private: -ldl
```

After that change the output of pkg-config to:
```
$ pkg-config --cflags epoxy
-DLINUX -DEGL_API_FB -DWL_EGL_PLATFORM
```

Which makes the previous test case build fine by just passing ``` $(pkg-config --cflags epoxy) ``` to the build system

I guess the list of library names added to ```Requires.private``` entry on the `pkg-config` file should be generated at configure/build time depending if glx or egl is enabled (or not).

Not sure if ```glesv2``` or ```gl``` should be added also to the list or not.

Note this doesn't change the output that is passed to the linker
```
$ pkg-config --libs epoxy
-lepoxy
```

That is the difference between ``` Requires ``` and ```Requires.private```

The ```Requires.private``` setting only affects to the ```cflags``` that is what we want here.

**Comment by ebassi** [comment]
Considering that libepoxy dlopen's things libraries on all platforms that also use pkg-config, I don't think this is at all correct — i.e. the compiler flags for dependent projects should not be provided by libepoxy at all.

If you're building for a platform with a closed drivers, you probably want to inject those compiler flags in your build environment, not as the result of compiling against libepoxy.
