### ISSUE TITLE
Add a thread-safe interface?

### ISSUE THREAD

**Issue by haasn** [anholt/libepoxy#142]
It seems like libepoxy is designed to load everything statically using whatever GL interface happens to be available at build time. This makes it rather useless for libraries, which may need to be used from different threads, perhaps even with different GL implementations. For example, afaict it would be perfectly valid for something to be using GLX and EGL in the same process; and you can't just mix and match GLX and EGL versions of functions (which could even be coming from different drivers).

The apparently normal approach to such GL function loaders in libraries is to explicitly fill a dispatch table using a user-provided `getProcAddress` callback. For an example, consider this GL dispatch table in mpv:

https://github.com/mpv-player/mpv/blob/master/video/out/opengl/common.h
https://github.com/mpv-player/mpv/blob/master/video/out/opengl/common.c

Or this one in VLC:
https://git.videolan.org/?p=vlc.git;a=blob;f=modules/video_output/opengl/converter.h;h=3acbf6911d7e2a38b06418a3a84f1b15aefe61c7;hb=HEAD#l102

These redundant, NIH'd “OpenGL function loaders” are exactly the sort of thing that libepoxy ought to replace; but the only reason it can't is due to the lack of an appropriate thread-safe interface/loading mechanism.

Do you think it would be possible to expand libepoxy to handle this kind of scenario?

**Comment by ebassi** [comment]
Epoxy already uses a dispatch table on WGL; on GLX and EGL the specification is already clear that the function pointers must be context-independent. See also [this comment](https://github.com/anholt/libepoxy/issues/127#issuecomment-327777198). The Apple GL situation is a bit more fuzzy, and would require testing, but we can extend the WGL dispatch table to also work on Apple.

Is there an actionable issue, here? Have you tried using libepoxy on different platforms and with multi-threaded applications, and experienced issues?

**Comment by nwnk** [comment]
There is an almost valid point here, which is that if you have multiple GL libraries (implicitly: from different vendors/drivers) then you really don't have any reason to expect eglGetProcAddress from each to return functions pointers that would work with the other.

I'm personally not interested in solving that problem, given that [libglvnd](https://github.com/NVIDIA/libglvnd) exists to solve exactly that problem.

**Comment by haasn** [comment]
> Is there an actionable issue, here? Have you tried using libepoxy on different platforms and with multi-threaded applications, and experienced issues?

No, I'm just worried about using libepoxy in my library since it feels thread unsafe-y. But I guess I could give it a shot and see how far I get.

**Comment by haasn** [comment]
Actually, there's another issue I'm running into here: Without a dispatch table / getProcAddress callback, how am I supposed to know which version of GL to initialize in a platform-independent library? I tried just linking to libepoxy and then running glFoo commands, but the functions don't seem to return anything (e.g. `epoxy_gl_version()` returns 0). I guess that's because it hasn't actually loaded the functions yet internally - but I don't really understand how to make libepoxy do that in a platform independent way.

With an API based on a dispatch table and explicit call back, this is not an issue because I can just ask the user to provide me with a GetProcAddress callback and do all loading based on that, without having to worry about the platform.

**Comment by nwnk** [comment]
> Never mind, seems like it's enough if there's an OpenGL context currently bound to the thread?

Correct. epoxy doesn't automate setting up the context, and uses the one you've created to glue up all the various symbols.

Closing this issue as I don't think there's anything further we need to do here. Please reopen if you encounter any further thread safety issues.
