### ISSUE TITLE
RFE: Add abstractions around context handling

### ISSUE THREAD

**Issue by nwnk** [anholt/libepoxy#150]
In re issue #149, it might be useful to add some API to handle the winsys calls for context creation etc. For example it'd be nice if the app didn't have to hunt for whether `glXCreateContextAttribs` is available, or handle fallbacks when some context attribute like no-error or no-flush is unavailable.

There's probably code we could steal for this in xserver or glew.

**Comment by anholt** [comment]
I'm not excited about this -- I'd like this library to stay as a dlsym-vs-getprocaddress-and-aliasing helper.  I do think there's space in our ecosystem for a good GL helper library, though -- not just context creation, but things like "can you do VAOs please, even if this GL doesn't do VAOs?"

**Comment by nwnk** [comment]
Well I'm not super excited about writing it, so, closing.
