### ISSUE TITLE
Redundant glXGetProcAddressARB-calls severely reducing performance

### ISSUE THREAD

**Issue by thrimbor** [anholt/libepoxy#171]
This may be something stupid on my side, but maybe someone can shed some light on this.

I recently tried to use libepoxy in an attempt to port an SDL+OpenGL based game to Windows (the relevant commit is [this one](https://github.com/thrimbor/Hurrican/commit/3b37d98c0eda2808bc456e75246991911303a016)).
However, using libepoxy on Linux resulted in a drastic performance loss: The fps dropped from over 3000 to ~500, even dropping below 30 in some areas - which is extremely strange for such a simple renderer.

Further analysis showed that libepoxy does a significant amount of redundant GL-calls (glXGetCurrentContext, glGetString and glXGetProcAddressARB) before every call to an OpenGL function ([here](https://gist.github.com/thrimbor/d6f5e163ca1d25398a1c1631c2e97dec) is an analysis of a single frame).

I ran it on Arch Linux with a GTX 970 (390.48 driver), and I tried libepoxy 1.5.0 and 1.5.1 (and 1.4.0 a while back, I think). Arch Linux doesn't seem to do anything special when building the package.

I'm not sure what the problem is here, I expected libepoxy to only query the addresses once. Are there known problems combining libepoxy with SDL (version 1), or am I hitting a bug here?

**Comment by ebassi** [comment]
Epoxy needs to test the version and supported extensions before dispatching a function, as it takes care of handling the different API:

> Knows about function aliases so (e.g.) `glBufferData()` can be used with
> `GL_ARB_vertex_buffer_object` implementations, along with GL 1.5+
> implementations.

We cannot really cache the version and extension checks once performed, because you could call the same function using difference contexts; we could find a way to cache things a bit better, though.

On the other hand, querying the version and extensions should return static data and it's typically not a synchronization point: it should affect performance in a drastic way. Are you enabling some debugging state?

**Comment by ebassi** [comment]
I do wonder, though, if you're using OpenGL < 3.2 and the old fixed function pipeline — and you're calling `glGetString()` between `glBegin()` and `glEnd()` pairs with some sort of debugging enabled.

Can you create a small, self-contained example?

**Comment by nwnk** [comment]
This looks more like the resolver is being called every time. As if the variable holding the function pointer wasn't being updated.

**Comment by nwnk** [comment]
@thrimbor if you could test the patch in #173 that'd be awesome.

**Comment by thrimbor** [comment]
Sorry for not replying earlier, didn't have much time to spend on this in the last few days.

@nwnk That patch works very well, performance is now almost identical to not using libepoxy!

@ebassi The code can be configured to use OpenGL 1.1 or 2.1, but it uses glVertexPointer and friends instead of glBegin/glEnd. My reason for using libepoxy was to get rid of the manual function pointer handling for shaders and compressed textures. Afaik the code doesn't use any special debugging stuff.

**Comment by nwnk** [comment]
@thrimbor well I'm glad it helps, but I'm concerned that it'd be needed. Your code doesn't look like it's trying to save function addresses, so I would naively think that calling `glVertexAttribArray` on a second function entry would see the updated value of `epoxy_glVertexAttribArray`.

I wonder if this is a funny interaction with linking with `-Bsymbolic`, if our resolver is updating the value of the copy of the function pointer slot _in libepoxy_ as opposed to the copy relocation slot in the main executable.

**Comment by nwnk** [comment]
@thrimbor could you test a build of libepoxy without the patch from #173, but with the `-Bsymbolic`s in `src/meson.build` changed to `-Bsymbolic-functions`? I think that should make epoxy bind its function calls to itself but still use the copy relocs for data.

**Comment by thrimbor** [comment]
@nwnk Changing that has the same positive effect on performance.

**Comment by ebassi** [comment]
Opened #174 with the linker flag change only, but given the testing, we should likely merge both.
