### ISSUE TITLE
Problem with dependancy versions with yum update

### ISSUE THREAD

**Issue by cmh8133** [anholt/libepoxy#175]
yum update
Loaded plugins: langpacks, rhnplugin, ulninfo
This system is receiving updates from ULN.
Resolving Dependencies
--> Running transaction check
---> **Package libepoxy.x86_64 0:1.3.1-1.el7 will be updated**
--> Processing Dependency: libepoxy(x86-64) = 1.3.1-1.el7 for package: libepoxy-devel-1.3.1-1.el7.x86_64
---> **Package libepoxy.x86_64 0:1.3.1-2.el7_5 will be an update**
--> Finished Dependency Resolution
Error: Package: libepoxy-devel-1.3.1-1.el7.x86_64 (@ol7_latest)
           Requires: libepoxy(x86-64) = 1.3.1-1.el7
           Removing: libepoxy-1.3.1-1.el7.x86_64 (@ol7_latest)
               libepoxy(x86-64) = 1.3.1-1.el7
           Updated By: libepoxy-1.3.1-2.el7_5.x86_64 (ol7_x86_64_latest)
               libepoxy(x86-64) = 1.3.1-2.el7_5
           **Available: libepoxy-1.2-2.el7.x86_64 (ol7_x86_64_latest)
               libepoxy(x86-64) = 1.2-2.el7**
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by ebassi** [comment]
You should file a bug against the Linux distribution you're using.
