### ISSUE TITLE
libexpory-1.5 fails to build with uclibc

### ISSUE THREAD

**Issue by stefson** [anholt/libepoxy#181]
when compiling libpoxy-1.5 with uclibc, the build breaks with this error: 

```../libepoxy-1.5.2/test/egl_has_extension_nocontext.c: In function 'main':
../libepoxy-1.5.2/test/egl_has_extension_nocontext.c:58:24: error: implicit declaration of function 'strdup' [-Werror=implicit-function-declaration]
         an_extension = strdup(extensions);
                        ^~~~~~
../libepoxy-1.5.2/test/egl_has_extension_nocontext.c:58:24: warning: incompatible implicit declaration of built-in function 'strdup'
```
I added the build log and a log with the most important os libs and compilers. 

[full build log](https://github.com/anholt/libepoxy/files/2109973/build.log.zip)
[emerge --info](https://github.com/anholt/libepoxy/files/2109992/emerge-info.zip)

libepoxy 1.4 is just fine by the way

**Comment by ebassi** [comment]
`egl_has_extension_nocontext.c` had that `strdup()` call since commit 0270c800 in 2013, i.e. since 1.4.0, and uclibc has a `strdup()` implementation – though it seems it's gated on `_XOPEN_SOURCE_EXTENDED`.

**Comment by ebassi** [comment]
@stefson could you try building #182?

**Comment by stefson** [comment]
yes, it does build now! thanks for the fast fix :)
