### ISSUE TITLE
why use epoxy

### ISSUE THREAD

**Issue by MaliciouSSymbol** [anholt/libepoxy#185]
why
```c
#include <epoxy/gl.h>
#include <epoxy/glx.h>
```
instead of
```c
#include <GL/gl.h>
```

**Comment by ebassi** [comment]
Hi; this is an issue tracker, and does not really work as a way to ask questions about the nature of Epoxy.

"Why use epoxy" — I assume you haven't read the [README](https://github.com/anholt/libepoxy/blob/master/README.md) file with the rationale for using Epoxy.

As for the header to include: Epoxy provides the GL API through wrappers, so it can load symbols on demand; check for supported extensions; and map aliases. This cannot happen when using the GL headers.
