### ISSUE TITLE
autogen.sh should use mkdir -p m4

### ISSUE THREAD

**Issue by dweineha** [anholt/libepoxy#186]
autogen.sh isn't idempotent; it tries to create the m4 directory, and if it exists it fails.

Reasonably we should only fail if creation fails due to permissions or similar, not if the directory already exists.

Suggested fix is to use mkdir -p m4 || exit 1

This way we'll still exit if the directory cannot be created due to permission issues, I/O errors, etc., but succeed if the directory already exists.

**Comment by ebassi** [comment]
I'd actually always remove the `m4` directory unconditionally and re-create it. The `autogen.sh` script should always result in a clean slate.

The Autotools build is kind of low on the list of priorities. Care to open a pull request? :wink:

**Comment by ebassi** [comment]
Nothing happened in over a year, and I'm in the process of landing #212 which removes the Autotools build entirely, so I think we can safely close this issue.
