### ISSUE TITLE
Questions about building library for mobile platforms(iOS & Android)

### ISSUE THREAD

**Issue by LittleC** [anholt/libepoxy#198]
Sorry if this is the wrong place to ask questions.

I'm new to libepoxy and is trying to integrate it with my own project, which would use OpenGL for rendering for both desktops(mac/windows) and mobiles(iOS/Android).

Currently, I've successfully generated libraries for desktops using instructions in README, and also tested that they works perfectly.
But I'm not aware of how to create libraries for mobile platforms.
Is there any resource that I can refer to? ( Have searched over Internet but no good...)

Thanks in advance.

**Comment by ebassi** [comment]
> Sorry if this is the wrong place to ask questions

This is an issue tracker, so it'd be better to ask on other venues where people working on libepoxy are usually gathered, like the `#xorg-devel` IRC channel on freenode.

> But I'm not aware of how to create libraries for mobile platforms.

I honestly have never built libepoxy for Android; I know that some people have been able to cross-compile it using the Android NDK, but I don't know how.

Hopefully this should give you a start on how achieve what you want.
