### ISSUE TITLE
MESA Swap Support is Undeclared

### ISSUE THREAD

**Issue by RobertBColton** [anholt/libepoxy#201]
Hi again, I have an issue with using glx/libepoxy on Ubuntu 14 (Travis CI instance). As it stands `glxSwapIntervalMESA` does not seem to be declared by `epoxy/glx.h` which is giving me a compile error.
```
g++ -std=c++11 -Wall -s -O3 -fno-rtti -fno-exceptions -DCOLLISION_NONE -IPlatforms/xlib/Info -IGraphics_Systems/OpenGL1/Info -IAudio_Systems/None/Info -ICollision_Systems/None/Info -IWidget_Systems/None/Info -INetworking_Systems/None/Info -IUniversal_System/Info -I. -I/tmp/ENIGMA/ -I../../shared  -MMD -MP -c -o /tmp/ENIGMA/.eobjs/Linux/Linux/GNU_GCC_G++/Run/Bridges/xlib-OpenGL/graphics_bridge.o Bridges/xlib-OpenGL/graphics_bridge.cpp
Bridges/xlib-OpenGL/graphics_bridge.cpp: In function ‘void enigma_user::set_synchronization(bool)’:
Bridges/xlib-OpenGL/graphics_bridge.cpp:133:35: error: ‘glXSwapIntervalMESA’ was not declared in this scope
       glXSwapIntervalMESA(interval);
                                   ^
```

**Comment by ebassi** [comment]
First things first: the version of Mesa on Travis is hopelessly out of date. I strongly encourage you to use a newer version of Mesa in your CI environment, like we do in Epoxy itself.

Additionally, you really don't want to use [GLX_MESA_swap_control](https://www.khronos.org/registry/OpenGL/extensions/MESA/GLX_MESA_swap_control.txt); you should use [GLX_EXT_swap_control](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_swap_control.txt) instead.

I can see the symbol being defined in `glx.h` when building epoxy on Debian stable and a recent Fedora image, in any case. Are you sure you're including `epoxy/glx.h` and not `GL/glx.h` somewhere?

**Comment by RobertBColton** [comment]
Hi @ebassi and thank you for the advice on mesa, I can and will look into that. Let me mention that this is somewhat related to #200 just in the sense that it's part of the same effort of [switching our game engine off of glew and using libepoxy](https://github.com/enigma-dev/enigma-dev/pull/1602) so we can get OpenGL ES going too while simplifying the context handling.

With that said, let me tell you how we were using `glSwapControlMESA`. Basically, with glew/glxew we were handling the fallbacks ourself (checking for various swap control features before picking one that works).
https://github.com/enigma-dev/enigma-dev/blob/2cc99695e0929a2ca84becdac62acc36b18f6619/ENIGMAsystem/SHELL/Bridges/xlib-OpenGL/graphics_bridge.cpp#L90

Now let me ask you the question that should help me resolve this. So, I understand libepoxy handles fallbacks and dynamically initializes the context. This leads me to think that I should not have to explicitly check all of those extensions. Is that true? Will libepoxy's glx look for the mesa swap control if that's the only one available? If that's true, then I should be able to just delete all that and use `glxSwapInterval` with no MESA suffix?

**Comment by anholt** [comment]
epoxy only automatically falls back to aliased providers of the same functionality (for example glVertexAttrib4fvNV() vs glVertexAttrib4fv() -- you get to detect that either the extension or the core support is present, then use one name throughout your code).  None of the swap interval glx functions are defined to be aliases of each other, so you have to actually use the right one for the extension you've detected, or you may abort.

libepoxy does not dynamically initialize the GL context.  It only dynamically loads the function pointers.

**Comment by RobertBColton** [comment]
Ok, so to clarify, how can I get access to `glXSwapIntervalMESA(interval);` as a fallback for when the extension isn't available? How can I resolve the original error?

We actually run a CI test harness on Travis that uses MESA to run our graphics engine. Then we use an image diff tool to look for regressions. So, we'll need to keep our MESA fallback.

**Comment by ebassi** [comment]
@RobertBColton If the `GLX_MESA_swap_control` extension is not available, then there won't be `glXSwapIntervalMESA()` available. Additionally, if your GL driver is not Mesa and it does not have `GLX_MESA_swap_control` compatibility, you will need to check if the symbol is defined at compile time as well:

```cpp
// Compile time check; epoxy will define glXSwapIntervalMESA to its own wrapper
#if defined(glXSwapIntervalMESA)
  // Run time check
  if (epoxy_has_glx_extension ("GLX_MESA_swap_control"))
    glXSwapIntervalMESA (interval);
#endif
```

**Comment by RobertBColton** [comment]
@ebassi Thank you so much, closing as resolved because I now figured out what's going on. Basically, a year ago you guys added `glXSwapIntervalMESA` in fe62e02231a4e527a896784bdb293c644a94320f but the Travis Ubuntu 14 we use hasn't gotten the newer version of epoxy. So yes, the correct thing to do is a compile time check. Alternatively/later we could also manually load the function ourselves, but we'll deal with that when it comes up.
