### ISSUE TITLE
OpenGL ES Registry Missing

### ISSUE THREAD

**Issue by RobertBColton** [anholt/libepoxy#205]
I am looking to use libepoxy also for loading OpenGL ES, but I noticed that among your registry entries you guys only have `gl.xml` which is part of the combined registry.
https://www.khronos.org/registry/OpenGL/index_es.php

Now, I am confused about which header to include for using OpenGL ES, where I would have only the extension points for OpenGL ES and not the ones for OpenGL. I would like it to be such that calling OpenGL functions not supported by OpenGL ES would be a compile-time error. What can I do?

**Comment by anholt** [comment]
Sorry, we don't have an option for that.  Applications may call either desktop or ES from the same code (that's part of the point of this library!), and just like with extensions, it's up to you to make sure that you only take code paths that are valid for your particular context.

**Comment by RobertBColton** [comment]
Understood, thanks, I just wanted clarification!
