### ISSUE TITLE
Can a library use Epoxy without interfering with using applications?

### ISSUE THREAD

**Issue by MarkCallow** [anholt/libepoxy#207]
I have a library with a few functions that use OpenGL {,ES}. Until now they've been in separate compilation units so only apps that were using the OpenGL functions would need to link with OpenGL. I have had to make some changes (think virtual functions) that mean those functions will be included even in apps that will never call them. To avoid a dependency on OpenGL for those apps, I need to runtime load all the function pointers, if an OpenGL-using function is called. Note the the app is responsible for creating the OpenGL context and making it current before calling the library when it intends to use those functions.

Can my library use Epoxy for the runtime loading without interfering with whatever the application is doing to resolve the OpenGL functions it is using?

Can Epoxy work with a context it did not create?

Are the dependencies listed in README.md necessary at run time or only build time?

What is the compiled code size? I don't want run-time loading to inflate the library size too much.

**Comment by MarkCallow** [comment]
Ping!

**Comment by ebassi** [comment]
> Can my library use Epoxy for the runtime loading without interfering with whatever the application is doing to resolve the OpenGL functions it is using?

Epoxy generates symbols that map to the GL function names, as defined by the OpenGL registry; if you include "epoxy/gl.h" and then use, say, `glGenBuffers`, you will actually be calling `epoxy_glGenBuffers()`, which will trampoline into epoxy and then into whatever GL library was dynamically loaded by epoxy.

> Can Epoxy work with a context it did not create?

Epoxy doesn't create any context. It's purely a library that loads the appropriate GL shared library for you.

> Are the dependencies listed in README.md necessary at run time or only build time?

The dependencies listed are build-time ones; of course, if you don't have any GL library at run time, things will fail pretty quickly.

> What is the compiled code size? I don't want run-time loading to inflate the library size too much.

Epoxy creates a trampoline for every symbol in the GL registry, plus bits and blobs for error handling. The end result is around 1MB, stripped, and 5MB unstripped.

**Comment by MarkCallow** [comment]
So the answer to my first question is yes?

Thanks for the information.

**Comment by ebassi** [comment]
> So the answer to my first question is yes?

The answer to your question is: it depends.

If an application is trying to `dlopen()` libGL.so and then defines a bunch of symbols like:

```cpp
#define glGenBuffers(n,buffers) some_vtable->glGenBuffers((n), (buffers)
```

Then the symbol will conflict if `epoxy/gl.h` is also included. Otherwise: no, there won't be any conflict. Of course, doing the work twice is not really useful, and epoxy encodes a lot of knowledge in how to safely retrieve the appropriate function pointers depending on the supported extensions and version of the underlying GL machinery.

If you depend on epoxy it's highly recommended that you tell people using your code that they should also use epoxy, to simplify and centralise the GL loading code and the symbol resolution.

**Comment by MarkCallow** [comment]
> ```
> #define glGenBuffers(n,buffers) some_vtable->glGenBuffers((n), (buffers)
> ```

Why would this conflict? Wouldn't Epoxy be using `some_other_vtable`? I suppose there is a remote chance some other loader chooses the same name for its vtable, but other than that?

The only other potential conflict I see is redefining `glGenBuffers` but my library will not include whatever header the app may be using and the headers my library exposes will not include `epoxy/gl.h` so there won't be a problem.

**Comment by ebassi** [comment]
I said:

> Then the symbol will conflict if `epoxy/gl.h` is also included

Because epoxy defines `glGenBuffers` itself.

**Comment by MarkCallow** [comment]
Thanks. I think I'll give Epoxy a try.
