### ISSUE TITLE
It shows errors when I use autogen.sh

### ISSUE THREAD

**Issue by yungcross** [anholt/libepoxy#222]
I use autogen.sh.
But it will show errors below:

checking for KHR/khrplatform.h... no
checking if gcc supports -Wno-int-conversion... yes
./configure: line 19246: syntax error near unexpected token `EGL,'
./configure: line 19246: `    PKG_CHECK_MODULES(EGL, egl)'

How to fix this problem.

Thank you.

**Comment by ebassi** [comment]
You seem to be missing the `pkg.m4` macro file, which comes with pkg-config.
