### ISSUE TITLE
wayland session failed with a dock for lenovo T460

### ISSUE THREAD

**Issue by bdouxx** [anholt/libepoxy#234]
hi,

OS: Gentoo KDE.
kde-plasma: 5.19.5
kde-frameworks: 5.74.0
kde-apps: 20.04.3
dev-libs/plasma-wayland-protocols : 1.1.1
dev-libs/wayland : 1.18.0
dev-libs/wayland-protocols : 1.20
dev-qt/qtwayland : 5.15.1
kde-frameworks/kwayland : 5.74.0
kde-plasma/kwayland-integration : 5.19.5
kde-plasma/kwayland-server : 5.19.5

laptop lid opened. 
X11 -> ok
Wayland  -> ok

laptop lid closed, on a lenovo dock with hdmi screen.
X11 -> ok
Wayland  -> session crash just after login

error in file ~/.local/share/sddm/wayland-session.log
kwin_wayland: ../libepoxy-1.5.4/src/dispatch_common.c :863 : epoxy_get_proc_address:  l'assertion « 0 && "Couldn't find current GLX or EGL context.\n" » a échoué.

I don't know if it's a problem with kwin implementation, or with libepoxy.

**Comment by nwnk** [comment]
epoxy doesn't change the current context without being told to, so this is almost certainly a kwin bug. Is there anything else in `wayland-session.log` before this?

**Comment by bdouxx** [comment]
Hi,

new test and full log for 3 configurations, and all package updated: 
* laptop only
[wayland-session.log_computer_only_ok.txt](https://github.com/anholt/libepoxy/files/5648638/wayland-session.log_computer_only_ok.txt)
* laptop an hdmi
[wayland-session.log_computer_and_hdmi_ok.txt](https://github.com/anholt/libepoxy/files/5648637/wayland-session.log_computer_and_hdmi_ok.txt)
* hdmi only
[wayland-session.log_hdmi_only_ko.txt](https://github.com/anholt/libepoxy/files/5648639/wayland-session.log_hdmi_only_ko.txt)

Do you need anything else?

**Comment by bdouxx** [comment]
problem solved with recent upgrade

OS: Gentoo KDE.
kde-plasma: 5.21.4
kde-frameworks: 5.81.0
kde-apps: 20.12.3
dev-libs/plasma-wayland-protocols : 1.1.1
dev-libs/wayland : 1.19.0
dev-libs/wayland-protocols : 1.20
dev-qt/qtwayland : 5.15.2
kde-frameworks/kwayland : 5.74.0
kde-plasma/kwayland-integration : 5.21.4
kde-plasma/kwayland-server : 5.21.4
media-libs/libepoxy: 1.5.5
