### ISSUE TITLE
cannot open source file "epoxy/glx.h"

### ISSUE THREAD

**Issue by jhon-elen** [anholt/libepoxy#267]
cannot open source file "epoxy/glx.h" in vscode. I am trying to compile with M1 apple chip

<img width="990" alt="Screen Shot 2022-01-10 at 00 43 54" src="https://user-images.githubusercontent.com/58744960/148722754-2664407f-e8c3-499a-aa49-6df2c03efa69.png">

<img width="869" alt="Screen Shot 2022-01-10 at 00 47 42" src="https://user-images.githubusercontent.com/58744960/148723076-746945e6-fb6c-415d-b945-24b7f365196c.png">

**Comment by ebassi** [comment]
You'll have to set your include path. Libepoxy ships with a [pkg-config file](https://www.freedesktop.org/wiki/Software/pkg-config/) that defines the compiler and linker flags to be used.

**Comment by jhon-elen** [comment]
I got same error, 'epoxy/glx.h' file not found in command-line

<img width="929" alt="Screen Shot 2022-01-11 at 23 58 38" src="https://user-images.githubusercontent.com/58744960/149066627-a684ba45-bcb8-4365-9d0f-6d845e225864.png">
