### ISSUE TITLE
Add link to docs from the readme ?

### ISSUE THREAD

**Issue by stuaxo** [anholt/libepoxy#281]
Are the docs hosted somewhere ?

I can see there's some reference to doxygen, so I guess they are up somewhere - it would be good to have a link to them from the README if this is the case.

**Comment by ebassi** [comment]
The documentation is not hosted, as it would require adding a GitHub pages branch and telling GitHub to publish the docs.

You can build the API reference of libepoxy locally, though.

**Comment by stuaxo** [comment]
Cheers, I'll give this a go.

**Comment by stuaxo** [comment]
What's the best way of invoking doxygen to generate html docs, is there a meson/ninja command ?

**Comment by ebassi** [comment]
From the `meson_options.txt` file:

```
option('docs',
       type: 'boolean', value: false,
       description: 'Enable generating the Epoxy API reference (depends on Doxygen)')
```

If you configure libepoxy's build with `-Ddocs=true` then you'll get the documentation in the build directory.
