### ISSUE TITLE
Hello triangle example

### ISSUE THREAD

**Issue by stuaxo** [anholt/libepoxy#284]
Hi,
   It would be good to have some very basic examples, e.g. "Hello triangle", since it looks like libepoxy is a nice modern set of bindings.

moderngl (a python gl binding), has a whole section on integrating it with other libraries[1] + it may be worth starting down this road, since I guess the GL context has to come from somewhere.

[1] - OT, but I'm a fan of integrations since the first time I saw this in a project; before this there wasn't much info in projects around using them with other things, pyimgui, moderngl have good examples and testing the integrations to make sure they work as expected

https://github.com/pyimgui/pyimgui#installation
https://github.com/moderngl/moderngl/blob/master/examples/integration_pycairo.py

PyCairo has an integration section in the docs, but I didn't include a link as I really need to find the time to improve it :)

**Comment by ebassi** [comment]
Epoxy is not a GUI toolkit, or a drawing API: it is a dispatch library for GL. I'm not entirely sure what a "hello triangle" example for libepoxy would look like: the entire point is that you don't have to deal with that at all.

**Comment by stuaxo** [comment]
Ah, maybe I have to go and do some reading, coming from python I'm not as familiar with what is happening here + how to compare this vs say GLVND.

Is this a good place to start reading?
https://docs.mesa3d.org/dispatch.html

Originally I thought this solved an issue around which GL library you would link to mesa/nvidia or whatever; I'm not quite as sure now.

**Comment by stuaxo** [comment]
Closing, since my question is based on faulty assumptions... I guess I still don't fully know what GL dispatch *is*...   I guess, it's around how you get some GL API, but I probably live too much in the high level world.

May be getting a tiny bit of free time to poke this again soon.
