### ISSUE TITLE
libexpoxy doesn't find eglQueryDmaBufFormatsEXT

### ISSUE THREAD

**Issue by matthiasclasen** [anholt/libepoxy#292]
The GTK output shows that EGL_EXT_image_dma_import_modifiers is listed in the extension string, and yet,
libepoxy claims that eglQueryDmaBufFormatsEXT is not available:

```
* Message: 06:56:35.431: For syntax highlighting, install the “highlight” program
EGL API version 1.5 found
 - Vendor: Mesa Project
 - Version: 1.5
 - Client APIs: OpenGL OpenGL_ES 
 - Extensions:
	EGL_ANDROID_blob_cache
	EGL_ANDROID_native_fence_sync
	EGL_EXT_buffer_age
	EGL_EXT_create_context_robustness
	EGL_EXT_image_dma_buf_import
	EGL_EXT_image_dma_buf_import_modifiers
	EGL_EXT_pixel_format_float
	EGL_EXT_present_opaque
	EGL_EXT_protected_content
	EGL_EXT_swap_buffers_with_damage
	EGL_IMG_context_priority
	EGL_KHR_cl_event2
	EGL_KHR_config_attribs
	EGL_KHR_context_flush_control
	EGL_KHR_create_context
	EGL_KHR_create_context_no_error
	EGL_KHR_fence_sync
	EGL_KHR_get_all_proc_addresses
	EGL_KHR_gl_colorspace
	EGL_KHR_gl_renderbuffer_image
	EGL_KHR_gl_texture_2D_image
	EGL_KHR_gl_texture_3D_image
	EGL_KHR_gl_texture_cubemap_image
	EGL_KHR_image_base
	EGL_KHR_no_config_context
	EGL_KHR_reusable_sync
	EGL_KHR_surfaceless_context
	EGL_KHR_swap_buffers_with_damage
	EGL_KHR_wait_sync
	EGL_MESA_configless_context
	EGL_MESA_drm_image
	EGL_MESA_image_dma_buf_export
	EGL_MESA_query_driver
	EGL_WL_bind_wayland_display
	EGL_WL_create_wayland_buffer_from_image
 - Selected fbconfig: R8G8B8A8
          high depth: R16G16B16A16 float
No provider of eglQueryDmaBufFormatsEXT found.  Requires one of:
    EGL_EXT_image_dma_buf_import_modifiers
```

**Comment by matthiasclasen** [comment]
It turns out my problem was: no current context.

It is suprising that that matters since these functions explicitly take the display to query.

**Comment by ebassi** [comment]
The state machine still requires a context bound to the display for querying actual capabilities. It's a GL footgun, unfortunately. At least, these days, you can bind a context without a windowing system surface…

**Comment by RAOF** [comment]
This is just a matter of code, right? The GL(ES) entry points require a current context to resolve, but by adding a different `GEN_EGL_THUNKS` implementation you *could* call (almost all - I'm looking at *you*, `NV_fence_sync`) the EGL functions that aren't explicitly modifying/querying an attribute of the currently-bound context (`eglBindAPI`, `eglGetCurrent*`, etc), no?
