### ISSUE TITLE
Fails to configure with emscripten

### ISSUE THREAD

**Issue by turol** [anholt/libepoxy#31]
Trying to configure for emscripten with:

emconfigure ./configure

results in error:
checking for EGL... no
configure: error: Package requirements (egl) were not met:

No package 'egl' found

Emscripten should not require anything special for EGL. Adding (empty) environment variables EGL_CFLAGS and EGL_LIBS has no effect, it still fails in the same way.

**Comment by anholt** [comment]
Do you not have an egl.pc for your environment?

**Comment by anholt** [comment]
(no response, appears to be just a bad build environment)
