### ISSUE TITLE
libepoxy requires EGL_KHR_reusable_sync for eglCreateSyncKHR()

### ISSUE THREAD

**Issue by djkurtz** [anholt/libepoxy#33]
eglCreateSyncKHR() and friends are defined by two EGL extensions:
  EGL_KHR_fence_sync and EGL_KHR_reusable_sync

However, in the egl registry, they are only listed for EGL_KHR_reusable_sync, with just a comment in EGL_KHR_fence_sync:
  https://github.com/anholt/libepoxy/blob/master/registry/egl.xml#L1627

However, it is possible for a libEGL to provide EGL_KHR_fence_sync but not EGL_KHR_reusable_sync.  This is in fact the case for the mali driver I am using.

In that case, libepoxy fails to resolve eglCreateSyncKHR():

DISPLAY=:0 /usr/local/piglit/lib/piglit/bin/egl_khr_fence_sync -fbo -auto
No provider of eglCreateSyncKHR found.  Requires one of:
    EGL extension "EGL_KHR_reusable_sync"
Aborted (core dumped)

Is there any reason why the same functions cannot be included for multiple extensions?

Note: I think this is only a problem for EGL <1.5, since 1.5 has EGL_KHR_fence_sync as a built-in extension.

**Comment by anholt** [comment]
Fixed by 85e5100d673bba0945fa097966160720a1f86a36
