### ISSUE TITLE
Add Support to Build libepoxy with Visual Studio

### ISSUE THREAD

**Issue by fanc999** [anholt/libepoxy#34]
Hi,

From the next stable version of GTK+ (3.16.0, and the current git master branch for it), we would start to use libepoxy so that it would make it simpler to make the OpenGL calls on various systems.

Since GTK+ supports building with Visual Studio, I would like to maintain that every part of the stack is buildable with Visual Studio as well, and I would like to propose the changes to libepoxy to make that happen, as libepoxy currentlydepends on C99 features and gcc-specific directives.

I will attach a series of patches that are needed for this process here, to hopefully make things not-too-hard to maintain.

With blessings, thank you!

**Comment by anholt** [comment]
I'm a terrible maintainer.  I just went looking through the patches now.  On Linux I'm getting 2 fewer tests passing (GLX_NON_APPLE_TEST_PROGS vs _TESTS I think), and I'd like to see a license on detect-msvc.mak, which is quite a bit of code to not have a license.  If you fixed those and force-pushed to your repo, I'd pull it (well, and I'd update COPYING with appropriate info as well).

**Comment by fanc999** [comment]
Hi,

Since I (later had) opened a pull request with issue #35, probably it might be good that further items about this part is directed there, so this becomes more-or-less a duplicate issue.  Will close this issue as a result.

With blessings, thank you!
