### ISSUE TITLE
Can't use egl-only libepoxy app with egl apitrace 

### ISSUE THREAD

**Issue by elmarco** [anholt/libepoxy#37]
libepoxy links with glx by default on Mesa/X, but those symbols are not exported by apitrace egltrace.so. I built a fake Android egl-only version by tweaking configure and CFLAGS, so far it seems to work. Feel free to correct me if I am doing something wrong.

**Comment by anholt** [comment]
It doesn't link against libGL (the GLX library), so I'm not sure what bug you're trying to say there is.

anholt@eliezer:anholt/src/libepoxy% ldd /usr/lib/x86_64-linux-gnu/libepoxy.so 
	linux-vdso.so.1 (0x00007fff799fe000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f55d6835000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f55d648c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f55d6d55000)

**Comment by elmarco** [comment]
The problem I have is better described by #68. My workaround is to disable some PLATFORM_HAS_GLX, and enable PLATFORM_HAS_EGL in other places. Ideally, this would be dynamic instead.
