### ISSUE TITLE
Epoxy solution for Visual Studio 2013

### ISSUE THREAD

**Issue by codekiddy2** [anholt/libepoxy#40]
Hello guys, I'm working on series of Visual studio solutions for gtkmm and it's dependency packages..
so I created Visual Studio solution to build latest libepoxy with latest msvc.
I made some changes though to the original files however, and if you have time to review the solution and give your opinion on what could be possibly wrong it would be great.

I made tests for release and debug builds, both x86 and x64 targets and it works just fine :)
https://github.com/codekiddy2/Visual-Studio-gtkmm/tree/Redesign/projects

**Comment by fanc999** [comment]
Hi codekiddy2,

As I am also getting libepoxy to work with Visual Studio (issues #55 and #56), can I find out where I can find your modifications to the libepoxy code, so that maybe you could look at my changes as well?  I couldn't find it from your link.

With blessings, thank you!

**Comment by codekiddy2** [comment]
Hi fanc999,
My latest commit to master -> https://github.com/codekiddy2/Visual-Studio-gtkmm/tree/master/projects was 3 months ago and I'm no longer active at my gtkmm repo compilation and it's dependencies.

My aim was to make build everything "the same way" by using Visual Studio solutions, and From what I remember about libepoxy the only modification was made to following files:
** Makefile.mak
line 43:
!include .\msvc-120\detectenv-msvc.mak

** detectenv-msvc.mak
line 25:
# Check to see we are configured to build with MSVC (MSDEVDIR, MSVCDIR or
# VCINSTALLDIR) or with the MS Platform SDK (MSSDK or WindowsSDKDir)
!if !defined(VCINSTALLDIR) && !defined(WINDOWSSDKDIR)
MSG = ^

line 89 trough line 100:
added compilation flags to be the same as the flags used by all other projects from my gtkmm repo as explained in https://github.com/codekiddy2/Visual-Studio-gtkmm/wiki/Properties

I made no changes to the code base itself, I just created Visual Studio solution so all that users of my repository have to do is download the repo and read the readme file and hit the "build" button.

Thank you for your interest!

**Comment by anholt** [comment]
Is there something that should be pulled for this bug report?

**Comment by ebassi** [comment]
As no comment was left in the last year and a half, let's close this issue.

Additionally, building Epoxy from Git using [Meson](http://mesonbuild.com) now supports generating Visual Studio project files.
