### ISSUE TITLE
misc issues

### ISSUE THREAD

**Issue by sylware** [anholt/libepoxy#48]
The release tarball, 1.2 at the time of written, misses the distribution generated files from the GNU autotools (=forgot to run autoreconf?)

On GNU/Linux/x11, libepoxy configuration should allow plain x11 (without/different from GL):
 - should defaults to build_egl=no and build_glx=no (or autodetect) in configure.ac
 - To reflect the above and allow compilation, dispatch_common.h should default to #define PLATFORM_HAS_EGL 0 and #define PLATFORM_HAS_GLX 0

(gtk+ is hard dependend on libepoxy even on plain x11 systems)

**Comment by anholt** [comment]
I'm not supporting building partial versions of the library in the build system.  libepoxy doesn't depend on EGL or GLX after build.

The new releases are built using make distcheck.  I think using un-version-controlled scripts distributed with tarballs is nuts, but apparently people like to do that.
