### ISSUE TITLE
Cannot Compile - Running autogen.sh produces errors

### ISSUE THREAD

**Issue by CAPTNCAPS** [anholt/libepoxy#60]
Running the autogen.sh file produces following errors:  
![Image of Error](http://i.imgur.com/4u4BYDK.png)

I am running Ubuntu 15.04 have the listed dependencies installed.
I am new to linux world and don't know how I can fix it, so I thought I'd report it.

**Comment by anholt** [comment]
You need libtool installed., as the errors are suggesting.
