### ISSUE TITLE
How to build on windows

### ISSUE THREAD

**Issue by RobotCaleb** [anholt/libepoxy#65]
The latest release doesn't appear to include prebuilt binaries and I can't figure out the right voodoo as a windows developer to build this.

**Comment by yaronct** [comment]
@RobotCaleb: I've made a pull request, adding makefiles and instructions for building with MSVC 2013, and fixing compiler errors and warnings (#62). Till it's merged, u can try to pull the changes from [my fork](https://github.com/yaronct/libepoxy) (branch "v1_stable"), which also contains a few bug fixes, especially for Windows.

**Comment by RobotCaleb** [comment]
@yaronct Thanks. I checked it out. I'm using VS2015 so I had to add a block to `detectenv-mscv.mak`
```
!elseif $(VCVERSION) > 1899 && $(VCVERSION) < 2000
VSVER = 14
C99_COMPAT_NEEDED = 0
```

That allowed it to try to build.
It tried to include files from a `EGL` folder, but I don't have such a folder.

```
Microsoft (R) Program Maintenance Utility Version 14.00.23026.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        c:\python27\python.exe gen_dispatch.py --dir .. ..\registry\gl.xml
        c:\python27\python.exe gen_dispatch.py --dir .. ..\registry\wgl.xml
        c:\python27\python.exe gen_dispatch.py --dir .. ..\registry\egl.xml
        cl /MD /O2 /Zi /I..\include /I..\..\vs14\Win32\include /Dinline=__inline dispatch_common.c dispatch_wgl.c dispatch_egl.c gl_generated_dispatch.c wgl_generated_dispatch.c egl_generated_dispatch.c /DEPOXY_EXPORTS  /link /DLL /DEBUG /opt:ref /pdb:epoxy-vs14.pdb /out:epoxy-vs14.dll /implib:epoxy.lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23026 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

dispatch_common.c
<snip>\libepoxy\include\epoxy/egl_generated.h(10): fatal error C1083: Cannot open include file: 'EGL/eglplatform.h': No such file or directory
dispatch_wgl.c
<snip>\libepoxy\include\epoxy/egl_generated.h(10): fatal error C1083: Cannot open include file: 'EGL/eglplatform.h': No such file or directory
dispatch_egl.c
<snip>\libepoxy\include\epoxy/egl_generated.h(10): fatal error C1083: Cannot open include file: 'EGL/eglplatform.h': No such file or directory
gl_generated_dispatch.c
<snip>\libepoxy\include\epoxy/egl_generated.h(10): fatal error C1083: Cannot open include file: 'EGL/eglplatform.h': No such file or directory
wgl_generated_dispatch.c
<snip>\libepoxy\include\epoxy/egl_generated.h(10): fatal error C1083: Cannot open include file: 'EGL/eglplatform.h': No such file or directory
egl_generated_dispatch.c
<snip>\libepoxy\include\epoxy/egl_generated.h(10): fatal error C1083: Cannot open include file: 'EGL/eglplatform.h': No such file or directory
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.
```

**Comment by yaronct** [comment]
@RobotCaleb: Sorry, you're right. Currently in order to build u must have EGL installed, which you can get [here](http://community.imgtec.com/developers/powervr/graphics-sdk/). I will fix it so that it's possible to build on Windows without EGL support.

Currently u can just change in "dispatch_common.h" the lines:

    #ifdef _WIN32
    #define PLATFORM_HAS_EGL 1
    #define PLATFORM_HAS_GLX 0
    #define PLATFORM_HAS_WGL 1
   #elif defined(__APPLE__)

to:

    #ifdef _WIN32
    #define PLATFORM_HAS_EGL 0
    #define PLATFORM_HAS_GLX 0
    #define PLATFORM_HAS_WGL 1
   #elif defined(__APPLE__)

And in "src/Makefile.vc" just delete everything with "EGL" in it. Plz tell me if you're still having trouble. I'll commit a more formal solution later. Actually I'm now working on building Epoxy with CMake, hopefully I'll commit it soon.

**Comment by RobotCaleb** [comment]
@yaronct: Okay, disabling EGL and deleting from Makefile.vc got it to build. Thanks

I'm installing EGL stuff you linked to try with that, too. Do I need the installation path for it on my PATH or is the path to EGL stuff set somewhere?

**Comment by yaronct** [comment]
In the installer, u don't have to check everything: Enough to check "PowerVR Tools -> PVRVFrame" and "PowerVR SDK -> Native SDK". Now, assuming u installed in the default location (feel free to change it), which is "C:\Imagination\PowerVR_Graphics\PowerVR_Tools" for the tools and "C:\Imagination\PowerVR_Graphics\PowerVR_SDK" for the SDK, u need to add to the compilation line in src/Makefile.vc:

/I C:\Imagination\PowerVR_Graphics\PowerVR_SDK\SDK_3.5\Builds\Include

(It's the line that starts with "$(CC)"). There's no need to add any linkage directory, as Epoxy doesn't link with EGL, but loads it at runtime. So, when running your app, if u want to use EGL / OpenGL ES, you'll have to add "C:\Imagination\PowerVR_Graphics\PowerVR_Tools\PVRVFrame\Library\Windows_x86_64" to your "PATH" (for Windows 64 bit) or "c:\Imagination\PowerVR_Graphics\PowerVR_Tools\PVRVFrame\Library\Windows_x86_32" (for Windows 32 bit). Of course, feel free to copy the DLL-s somewhere else.

**Comment by Nephatrine** [comment]
You're also free to check out [my fork](https://github.com/Nephatrine/libepoxy) which uses CMake for the build system. It can build successfully in both VC12 (2013) as well as MSYS2+MinGW and the WGL tests look good, though I haven't tried plugging it into a real application yet. I still need to get the CMake build working properly on other platforms, add an install target, and do some more in-depth testing (esp. with static builds).

**Comment by yavn** [comment]
@Nephatrine i used your CMake build with MinGW64 and it worked great for what I wanted to test. Thanks!

I mostly use Epoxy on Ubuntu, but it would be awesome to get CMake support into the upstream repo. It really makes things easier when you have to work with multiple platforms.

**Comment by Nephatrine** [comment]
@yavn - I'd polish it up a bit and see about submitting a PR, but my changes rely on PR #45 and #52 which haven't been pulled into the main repository yet. If they are objectionable to @anholt , then my fork will be too since I expose the same build options.

**Comment by yaronct** [comment]
@RobotCaleb, @Nephatrine, @yavn: I've also added an option to build Epoxy with CMake in [my fork](https://github.com/yaronct/libepoxy). @Nephatrine: Sorry, I did it before I knew u also had CMake support. Perhaps, at some point, it's worth merging our forks, as I also have several bug fixes (specifically for Windows) and built-in support for building with EGL support ("eglplatform.h" & "khrplatform.h" included in my repo). I'm not opening a PR here because I already have a very old PR which hasn't been pulled yet.

**Comment by RobotCaleb** [comment]
I've been using @yaronct build without EGL and it's working for us.

Optimally this isn't accomplished this way in the future, but I'm up and running for now. :)

Thanks

**Comment by Nephatrine** [comment]
@yaronct The primary reason I forked in the first place was to support compiling as a static library. If your fork supported that, I'd probably switch to using it. Until then, I'll probably just swipe some of the EGL stuff from your fork. What's the best way to test EGL on Windows though? I've only got nVidia cards and I don't think their Windows drivers have any EGL support (I might be wrong though).

**Comment by yaronct** [comment]
@Nephatrine: You're right, my fork didn't support static libs. But - it's your lucky day! I've added support for it, specially for u :) And also updated the doc to include instructions how to control building of shared/static libs, and how to install support for OpenGL ES / EGL. Enjoy!

**Comment by RobotCaleb** [comment]
@yaronct maybe I didn't call it right, but I couldn't figure out how to `clean`

Also, could you set it up to build to a bin folder or such?

**Comment by yaronct** [comment]
@RobotCaleb: [My fork](https://github.com/yaronct/libepoxy) now supports building with CMake, as well as building and running tests. Plz use it (checkout "master" branch). The "README.md" contains instructions how to build with CMake. Once you use CMake, you build the solution inside Visual Studio, and then everything will be built in the right directories, and also cleaning the solution should be simple.

Also, my fork already includes files pre-generated from the specs, so Python installation isn't required. Also, my fork includes "khrplatform.h" and "eglplatform.h", so now u can build with EGL support (which will happen by default) without having the EGL headers installed. However, to actually use EGL, u **will** need EGL installed and the "dll"-s in your "PATH" - read the "README.md" for detailed instructions.

Plz tell me if u have any more questions.

**Comment by ebassi** [comment]
In order to build Epoxy on Windows you need:

 * Python 3
 * [Meson](http://mesonbuild.com) — you can use `pip install meson` to install it

You can either generate Visual Studio project files, or use the Ninja backend.
