### ISSUE TITLE
release tarballs should ship a configure script and not depend on autoconf

### ISSUE THREAD

**Issue by rofl0r** [anholt/libepoxy#66]
autoconf is complex and errorprone (with regard to incompatible versions of m4 scripts etc) and places an additional burden on the end user that wishes to compile sw (plus additional dependencies), so it is common practice to generate the configure script on the developer's machine as part of the "make dist" workflow to ship a release tarball.

**Comment by yaronct** [comment]
@rofl0r: I've fixed this in [my fork](https://github.com/yaronct/libepoxy). I'm not opening a PR to this repo as I already have one open PR which I opened long ago and hasn't been pulled yet.

**Comment by rofl0r** [comment]
@yaronct your fix is to use cmake ? i despise cmake as it's a monstrous piece of software that takes longer to compile than gcc, is written in C++, and cannot create standalone makefiles. it ignores well-established UI standards (--prefix, --without-feature) and forces the user to spend a lot of time figuring out how to deal with it (once he got it to compile).

**Comment by yaronct** [comment]
@rofl0r: My fork supports both building with autotools ("configure" included, so the user doesn't have to have autotools installed) and building with CMake. U can use whatever u wish.

**Comment by rofl0r** [comment]
@yaronct where can the release tarballs of your fork be downloaded, and is your fork uptodate/compatible ?

**Comment by yaronct** [comment]
@rofl0r: In [my fork](https://github.com/yaronct/libepoxy), go to "releases", and download the one u want (usually with the highest version number, which is currently "v1.3.1_yaronct-3").

**Comment by ebassi** [comment]
Running `make distcheck` with the existing autotools build will generate a distribution tarball with `configure`. I assume the previous releases were snapshots of the Git repository.

For 1.3.2, I plan to do a full dist release.

Thanks for your bug report.

**Comment by rofl0r** [comment]
oh, this repo is maintained now? glad to hear!
