### ISSUE TITLE
should have api to safely query GL library existence

### ISSUE THREAD

**Issue by jku** [anholt/libepoxy#73]
I'm not totally sure where this issue should be fixed but here's the problem:
- GTK+ considers epoxy something they can depend on unconditionally without worrying about the GL implementation
- Installing GTK+ on systems without OpenGL is possible (dependency on epoxy is still there but not really a problem since epoxy is small and doesn't depend on much) 
- running GTK+ applications is a problem: Gdk initialization will try to initialize some visuals for GL and starts by running glXQueryExtension(). This will exit when libGL.so.1 is not present.

So: should epoxy have an api that can be used to check if an implementation is present (without epoxy exiting)? Or should GTK+ do this check on its own?

**Comment by smcv** [comment]
We're hitting this on Debian, including now the installer (!), so I'm going to put a patch together. I spoke to @ebassi on IRC and he said this would be useful to have.

Proposed APIs:

```
bool epoxy_has_{gl,glx,gles1,gles2,egl}_library (void);
```

**Comment by ebassi** [comment]
More something like:

```
  bool epoxy_has_platform_gl (void);
```

which would automatically check for GLX, WGL, AppleGL, or EGL, depending on the platform. Checking for GLES1, 2, 3 is already covered by `epoxy_is_desktop_gl()` and `epoxy_gl_version()`.

**Comment by smcv** [comment]
How do we know whether a non-Mac Unix caller wants GLX or EGL? (On Linux/*BSD/etc. you use GLX for X11, but EGL for Wayland/Mir/misc, right?)

**Comment by smcv** [comment]
To put this another way: what Gtk needs to know is whether glXQueryExtension() is going to work. If you are running under X11, and for some reason you have EGL drivers (Debian: libegl1-mesa) but not GLX (Debian: libgl1-mesa-glx), then a check for "do we have platform GL?" is going to succeed, but  glXQueryExtension() would still make Gtk exit abruptly.

**Comment by yaronct** [comment]
@smcv, you're right, we can't know which API is used to create an opengl context. So I think we have to b queried for something specific like "do we have api XXX?".

What then would b your requirements for gtk as for "XXX"? GLX? OpenGL?

**Comment by smcv** [comment]
At the moment GTK itself only needs to know whether `glXQueryExtension()` is going to crash the process, so `epoxy_has_glx()` or similar. Expected result: if there is `libGL.so.1` and we can dlopen it and we can get version information or whatever, return true; if not, return false; under no circumstances, call exit() :-)

For an application that actively **uses** GL, you know how the GL APIs break down better than I do. `epoxy_has_glx()` would cover the glXWhatever() class of APIs, and functions like `epoxy_has_gl_extension` cover checking whether particular extensions are available. Apart from those, what's left? Core GL functions that are neither extensions nor display-type-specific, like glGetString()?

The goal I would have if I was using libepoxy (which I'm currently not, except accidentally via GTK) is: for each symbol exposed by libepoxy, I want there to be a way that I can call it if it exists, but without libepoxy terminating my process. So if there are broad API groupings like "the core OpenGL API" where if you can rely on one you can rely on them all, I'd only need one checker function for the whole API grouping.

Or to put it another way, for each function `glFoo` exposed by libepoxy, I want there to be a function `epoxy_has_whatever` related to `glFoo` in some way, that I can use in code like this:

```
if (epoxy_has_whatever (some arguments I already know if I plan to call glFoo))
  {
    glFoo (...);
  }
else
  {
    /* some fallback */
  }
```

where in particular GTK wants this concrete example:

```
Display *display = ...;

if (epoxy_has_glx (display))
  {
    glXQueryVersion(display, ...);
    ... do something with the result, query some extensions for future reference, ...
  }
else
  {
    g_debug ("No GLX here");
  }
```

**Comment by yaronct** [comment]
@smcv: As I no longer have write access to this repo, you'll have to work it out with other ppl now, sorry.

**Comment by ebassi** [comment]
@smcv I've opened a new PR after your code review.

**Comment by ebassi** [comment]
> Or to put it another way, for each function glFoo exposed by libepoxy, I want there to be a
> function epoxy_has_whatever related to glFoo in some way, that I can use in code like this:

No, that would entirely defeat the point of Epoxy **and** it would make any use of GL through Epoxy incredibly slow.

Checking for windowing system support is enough; if you don't have access to the platform specific API — which is literally only the case with Linux, because [choice](http://islinuxaboutchoice.com) — then you cannot use GL at all. This is enough for dependant libraries and applications to decide whether or not to expose functionality related to OpenGL.

**Comment by smcv** [comment]
> for each function glFoo exposed by libepoxy, I want there to be a function epoxy_has_whatever related to glFoo in some way

I don't mean that I want there to be an epoxy_has_glXQueryExtension(), and so on for every function that I might possibly call - yes, that would be silly.

All I'm looking for is that for anything that a library user might want to do, there should be some path of checks that, if followed, guarantee that it won't call exit(1). 

If `epoxy_has_glx()` is enough to tell whether `glXQueryExtension()` is safe to use, `glXQueryExtension()` is enough to determine whether "core" GL functions are safe to use, and using "core" GL functions to query `GL_EXTENSIONS` is enough to determine which non-core things are safe to use, then that chain is enough.

**Comment by ebassi** [comment]
Yes: if the windowing system API is not available then you cannot create a GL context, which in turn makes it impossible to call any `gl*` API.

Inside GDK, the initialization code for the display connection is also responsible for checking if EGL (on Wayland) or GLX (on X11) are available before any GL calls are performed; if either one returns a negative result, then no GL call is made - thus it would avoid the `exit(1)` from libepoxy.
