### ISSUE TITLE
epoxy_gl_version() giving wrong results for LLVMpipe?

### ISSUE THREAD

**Issue by lbssousa** [anholt/libepoxy#76]
I'm palying with my [xf86-video-nested](../../../lbssousa/xf86-video-nested) fork, now trying to port current Xephyr implementation for GLAMOR support. I can make my driver load module `glamoregl`, required for calling function `glamor_init()`, but my nested Xorg always fails with the following message:

```
Require OpenGL version 2.1 or later.
```

My nested Xorg, like Xephyr, uses LLVMpipe software driver for OpenGL. Running `glxinfo | grep -i opengl` from my nested Xorg display gives me the following output:

```
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)
OpenGL version string: 3.0 Mesa 10.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
```

I know `glamor_init()` calls `epoxy_gl_version()` internally for checking supported OpenGL version. Is there a chance the later is giving wrong results for LLVMpipe?

**Comment by lbssousa** [comment]
Possible duplicate of #72

**Comment by yaronct** [comment]
@lbssousa: Could u try [my fork](https://github.com/yaronct/libepoxy) (branch "master")?

**Comment by ebassi** [comment]
The parsing code definitely detects `3.0 Mesa 10.3.2` as version 30 — i.e. (3, 0).

Issue #72 has also been fixed in the meantime.

Feel free to re-open if this happens with a build of Epoxy from a recent commit on the master branch.
