### ISSUE TITLE
Epoxy crashes if the code tries to call either wglChoosePixelFormatARB or wglCreateContextAttribsARB

### ISSUE THREAD

**Issue by esacree** [anholt/libepoxy#78]
The Epoxy function pointers for those 2 functions are always NULL, which causes the crash.

Is there any limitation on calling either wglChoosePixelFormatARB or wglCreateContextAttribsARB from  epoxy on Windows?   Calling wglGetProcAddress directly to look up these function pointers works.  Calling those 2 functions with the function pointers returned from wglGetProcAddress works.   It just doesn't work if the functions are called directly.  

The older call to wglCreateContext works as well as ChoosePixelFormat.  But I would like to get the ARB versions to get the compatibility profile to run on older video cards.  And access to more advanced profiles and pixel formats as well.

I had the same problem with GLEW.  This code is on Windows 10, Visual Studio 2015 Win32/X54 builds.  Using nVidia GeForce, Quadro latest drivers.  Also tried it on ATI R6 and Intel HD4600. 

I appreciate any insight on this issue.

**Comment by ebassi** [comment]
`wglCreateContext` will use the ARB variants, if they are defined. If you get a crash it would imply that you don't have access to those — i.e. they are not defined in the OpenGL implementation you are using.
