### ISSUE TITLE
Microsoft Visual Studio response to issue with CONSTRUCT macro crashing in Release mode on Windows

### ISSUE THREAD

**Issue by esacree** [anholt/libepoxy#79]
I logged the issue with Microsoft on the CONSTRUCT macro crashing in Release Mode on libEpoxy built with Visual Studio 2015.  Here's the response I received:

Greetings from Microsoft Connect!

This notification was generated for feedback item: Visual Studio 2015 C++ Compiler Optimization Bug - Release Build CONSTRUCT macro not executed - works in DEBUG Build which you submitted at theMicrosoft Connect site.

This is by design. The method that macro uses to implement a function call on load is unsupported, and not guarenteed to work in all future versions. The macro should dispense with the custom segment business and just directly initialize a global variable with a function call - the CRT will take care of calling the initializer function on load.

Another work around would be to mark the variable in the .CRT segment created by that macro as volatile. But again, I really recommend you move away from this approach entirely.

You may receive a general "Feedback Item Updated" notification as well, if any other changes were made by Microsoft.

Thank you for using Microsoft Connect!

Regards,

the Microsoft Connect Team

**Comment by ebassi** [comment]
This should go in #77 instead of a separate issue.
