### ISSUE TITLE
Support for loading angle under win32.

### ISSUE THREAD

**Issue by lygstate** [anholt/libepoxy#87]

**Comment by yaronct** [comment]
@lygstate: This repository of Epoxy seems to b currently no longer maintained. I try to maintain a [fork](https://github.com/yaronct/libepoxy) of Epoxy - other than being maintained, it also contains a number of bug fixes and improvements, notably it can be built as a static or shared library using cmake (while retaining autotools support), including running tests, and doesn't depend on `eglplatform.h` or `khrplatform.h`. If you're willing to open an issue at my fork it'll b appreciated.

**Comment by ebassi** [comment]
Does anything need to happen with this issue?

As far as I know, ANGLE just generates DLL files that you can ship in your environment.

@lygstate Could you please explain what do you need?

**Comment by ebassi** [comment]
GTK+ might end up using ANGLE on Windows soon-ish: see [this merge request](https://gitlab.gnome.org/GNOME/gtk/merge_requests/126). It seems that Epoxy works well enough with that, so I don't think we need to do anything on Epoxy's side: you need to build ANGLE as a dependency of your project, and Epoxy will load it just like it'd load any other GL library.
