### ISSUE TITLE
ABI report for libepoxy

### ISSUE THREAD

**Issue by aponomarenko** [anholt/libepoxy#89]
Hello,

Please take into account the ABI changes analysis report for the libepoxy library: https://abi-laboratory.pro/tracker/timeline/libepoxy/

Hope it will be helpful for users and maintainers of the library.

Thank you.

**Comment by ebassi** [comment]
Is there anything actionable in this bug report, outside of going to that web page?

Since Epoxy generates its API from the Khronos XML descriptions, there's not much we can do for ABI breakage involving those.
