### ISSUE TITLE
Is there a way to cross-compile this using mingw64?

### ISSUE THREAD

**Issue by DeadSix27** [anholt/libepoxy#91]
Version is from git master, newest commit: https://github.com/anholt/libepoxy/commit/15898325c1b3610dba737c311a33b28d83e343c7

Got it to configure just fine:
```
           EGL:         no
           GLX:         no
           WGL:         yes
        PYTHON:         python3
```

Steps:
touch configure.ac aclocal.m4 configure Makefile.am Makefile.in `Saw this recommended in another issue, since I have aclocal-1.15 and not aclocal-1.14`
./configure --host=x86_64-w64-mingw32 --prefix=/toolchain/cross/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-shared
make -j 4

However it fails during build with these error messages:

```
gl_generated_dispatch.c:122267:46: warning: 'epoxy_glWindowPos4svMESA' redeclared without dllimport attribute after being referenced with dll linkage
gl_generated_dispatch.c:122269:42: error: variable 'epoxy_glWriteMaskEXT' definition is marked dllimport
 EPOXY_IMPORTEXPORT PFNGLWRITEMASKEXTPROC epoxy_glWriteMaskEXT = epoxy_glWriteMaskEXT_global_rewrite_ptr;

```
And many more like that, tell me if you need a full config.log.

**Comment by yaronct** [comment]
@DeadSix27: The way that I recommend to build Epoxy now is using cmake (you'll have to use branch `master` though, not a release). I've tested MinGW-w64 targetting x86 / x64 and they work fine. If u still encounter problems plz report them.

**Comment by ebassi** [comment]
Hi @DeadSix27.

Epoxy has now a build system based on [Meson](http://mesonbuild.com). It comes with a cross-compilation file for Windows using the Fedora mingw64 presets. Just use:

```sh
mkdir _build && cd _build
meson --cross-file ../cross/fedora-mingw64.txt --prefix /usr/x86_64-w64-mingw32/sys-root/mingw --default-library static
ninja
```

and you should get a static build of Epoxy. If you use `--default-library shared` you'll get a shared library build, instead.

If you don't use Fedora, you can look at the cross-file in the Epoxy repository and set it up for your own cross-compilation environment; it should be pretty easy to do so.

Nevertheless, the issue you're reporting seem to imply some sort of symbol visibility issue. I cannot reproduce it with autotools or with Meson, so it may be an issue in how your toolchain is built.
