### ISSUE TITLE
Segfault when no GL available on X server

### ISSUE THREAD

**Issue by kapouer** [anholt/libepoxy#96]
Hi,
i'm reporting here a patch proposed downstream in fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1395366
and its (reverse !) patch here:
https://bugzilla.redhat.com/attachment.cgi?id=1221160

Care to comment and/or apply it to master ?

**Comment by ebassi** [comment]
Hi, thanks for your bug report!

The issue has been fixed in the master branch by commit a15a92c2cbe0a8f45a1ff6258b22957c17c7118e.

Feel free to re-open it if you can reproduce it again with a newly built Epoxy.
